#!/bin/sh

# Update A2osX over the Internet
# Bobbi 2021

if [ $# -ne 1 ]
  echo usage: update <buildnum>
  exit
fi
if [ -d ${ROOT}root/updates ]
else
  mkdir ${ROOT}root/updates
fi
echo Requesting A2osX build $1
httpget update.a2osx.net -U update.$1 -o ${ROOT}root/updates/update.$1
cd ${ROOT}
unpak root/updates/update.$1

