#!/usr/bin/env python3
"""
patch-image.py  —  Inject hardware-specific config into A2osX disk image.

Run after a successful cmake build:
    python3 cmake/patch-image.py

All user settings are in the CONFIGURATION section below.
"""

import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# ─── CONFIGURATION ────────────────────────────────────────────────────────────

# Path to built disk image (relative to repo root, or absolute)
IMAGE = "build/a2osx-full.po"

# ProDOS volume name inside the image
VOLUME = "/FULL800"

# Path to cadius executable
CADIUS = "cadius"

# ── Network ──────────────────────────────────────────────────────────────────
# Uthernet II MAC address — printed on the card (WIZnet OUI 00:08:DC:...)
UTHERNET2_MAC = "00:08:DC:XX:XX:XX"   # REPLACE with your actual MAC

# tcpip.conf injection:
#   False = omit tcpip.conf from image (use `netconfig` on first boot to get
#           DHCP lease; it saves result to /etc/tcpip.conf automatically).
#           Recommended if your router owns the DHCP range.  Add a DHCP
#           reservation by Uthernet II MAC address so the IP stays stable.
#   True  = inject a static tcpip.conf (fills in IP_* values below).
INJECT_TCPIP_CONF = False

IP_ADDRESS    = "192.168.1.XX"        # used only if INJECT_TCPIP_CONF = True
IP_NETMASK    = "255.255.255.0"
IP_GATEWAY    = "192.168.1.1"
IP_NAMESERVER = "192.168.1.1"
IP_DNSDOMAIN  = "local"

# ── Hostname ──────────────────────────────────────────────────────────────────
HOSTNAME = "bryanw-a2e"

# ── Users ─────────────────────────────────────────────────────────────────────
# Password is stored as plain MD5 (no salt) in /etc/passwd.
# Set BRYANW_PASSWORD to your desired password before running.
BRYANW_PASSWORD = "password"

# Additional users: list of (username, password, uid, gid, fullname, home)
# Root and guest are always included with standard hashes.
EXTRA_USERS = [
    ("bryanw", BRYANW_PASSWORD, 1001, 1001, "Bryan W", "/home/bryanw"),
]

# ── Slot layout ──────────────────────────────────────────────────────────────
# Slot 1: Mouse          — auto-detected by mouse.drv (no slot arg needed)
# Slot 2: Uthernet II    — loaded in INIT with MAC address
# Slot 3: TransWarp 1.4  — controlled by `acc` command, no driver needed
# Slot 4: SSC            — loaded if ENABLE_SSC = True
# Slot 5: ThunderClock   — handled by ProDOS FX boot loader, no A2osX driver
# Slot 6: Advanced Disk II / Yellowstone — block device, ProDOS handles it
# Slot 7: CFFA3000       — block device, ProDOS handles it

ENABLE_MOUSE = True     # insdrv mouse.drv
ENABLE_SSC   = False    # insdrv ssc.drv (serial terminal on slot 4)
SSC_PARAMS   = "9600,N,8,1,X"

# ─── END CONFIGURATION ────────────────────────────────────────────────────────


def md5hex(password: str) -> str:
    return hashlib.md5(password.encode()).hexdigest()


def to_cr(text: str) -> bytes:
    """Convert to CR-only line endings (Apple II convention)."""
    return text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r").encode()


def build_init() -> str:
    lines = [
        "# /etc/init — A2osX startup script",
        "# Auto-generated by scripts/patch-image.py",
        "#",
        "# Main virtual TTYs",
    ]
    for i in range(1, 9):
        lines.append(f"/sbin/getty /dev/tty{i} /sbin/login")

    lines += [
        "#",
        "# Hardware drivers",
    ]

    if ENABLE_MOUSE:
        lines.append("/sbin/insdrv mouse.drv")

    if ENABLE_SSC:
        lines.append(f"/sbin/insdrv ssc.drv {SSC_PARAMS}")
        lines.append("#  /sbin/getty /dev/com2 /sbin/login")

    lines += [
        f"/sbin/insdrv uthernet2.drv {UTHERNET2_MAC}",
        "#",
        "# Network",
        "/sbin/networkd libtcpip",
    ]

    return "\n".join(lines) + "\n"


def build_tcpip_conf() -> str:
    return (
        f"# /etc/tcpip.conf — static IP configuration\n"
        f"# Auto-generated by scripts/patch-image.py\n"
        f"address {IP_ADDRESS}\n"
        f"netmask {IP_NETMASK}\n"
        f"gateway {IP_GATEWAY}\n"
        f"nameserver {IP_NAMESERVER}\n"
        f"dnsdomain {IP_DNSDOMAIN}\n"
    )


def build_passwd() -> str:
    # Standard A2osX format: user:md5hash:uid:gid:gecos:home:/bin/sh
    # Root password hash from A2osX default (password: "a2osx" — change via passwd cmd)
    entries = [
        f"root:{md5hex('a2osx')}:0:0:A2osX Root:/root:/bin/sh",
        f"guest:{md5hex('guest')}:1000:1000:Guest Account:/home/guest:/bin/sh",
    ]
    for (user, pw, uid, gid, gecos, home) in EXTRA_USERS:
        entries.append(f"{user}:{md5hex(pw)}:{uid}:{gid}:{gecos}:{home}:/bin/sh")
    return "\n".join(entries) + "\n"


def build_hostname() -> str:
    return HOSTNAME + "\n"


def run_cadius(*args):
    cmd = [CADIUS] + list(args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  WARNING: cadius returned {result.returncode}")
        if result.stderr:
            print(f"  {result.stderr.strip()}")
    return result.returncode == 0


def inject_file(image: str, prodos_folder: str, filename: str, content: bytes,
                prodos_type: str = "04", aux: str = "0000"):
    """Replace or add a file in the ProDOS image."""
    with tempfile.TemporaryDirectory() as tmpdir:
        # cadius identifies type from '#TTAAAA' suffix
        local_name = f"{filename}#{prodos_type}{aux}"
        local_path = os.path.join(tmpdir, local_name)
        with open(local_path, "wb") as f:
            f.write(content)

        prodos_path = f"{prodos_folder}/{filename}"

        # Try REPLACEFILE first; fall back to ADDFILE for new files
        ok = run_cadius("REPLACEFILE", image, prodos_folder, local_path)
        if not ok:
            run_cadius("ADDFILE", image, prodos_folder, local_path)


def validate_config():
    errors = []
    if "XX" in UTHERNET2_MAC:
        errors.append("UTHERNET2_MAC still has placeholder XX bytes — update with your card's MAC")
    if INJECT_TCPIP_CONF and "XX" in IP_ADDRESS:
        errors.append("IP_ADDRESS still has placeholder XX — update with your static IP")
    if BRYANW_PASSWORD == "changeme":
        errors.append("BRYANW_PASSWORD is still 'changeme' — set a real password")
    return errors


def main():
    repo_root = Path(__file__).parent.parent
    image_path = str(repo_root / IMAGE)

    if not os.path.exists(image_path):
        print(f"ERROR: Image not found: {image_path}")
        print("Run 'cmake --build build' first.")
        sys.exit(1)

    # Validate — warn but don't block
    warnings = validate_config()
    if warnings:
        print("CONFIGURATION WARNINGS:")
        for w in warnings:
            print(f"  ! {w}")
        print()

    # Work on a copy so original is preserved
    patched = image_path.replace(".po", "-patched.po")
    shutil.copy2(image_path, patched)
    print(f"Patching: {patched}")
    print()

    files = [
        ("init",    build_init(),    "04"),
        ("passwd",  build_passwd(),  "04"),
        ("hostname",build_hostname(),"04"),
    ]
    if INJECT_TCPIP_CONF:
        files.append(("tcpip.conf", build_tcpip_conf(), "04"))

    folder = f"{VOLUME}/etc"
    for name, content, ftype in files:
        data = to_cr(content)
        print(f"  {folder}/{name}  ({len(data)} bytes)")
        inject_file(patched, folder, name, data, ftype)

    print()
    print(f"Done: {patched}")
    print()
    if warnings:
        print("Remember to update the placeholder values in the CONFIGURATION section.")


if __name__ == "__main__":
    main()
